### ISSUE TITLE
Переводится лишь первое предложение - Google переводчик

### ISSUE THREAD

**Issue by bikbov** [PavlikBender/ScreTran#3]
![hi3](https://github.com/user-attachments/assets/741dbfcf-32bb-4a42-bbbd-886deb4033e2)

**Comment by bikbov** [comment]
Поменял тип переводчика с Google на Яндекс, это помогло

**Comment by PavlikBender** [comment]
Привет, да я заметил эту проблему. Сломался гугл переводчик. Будет работать с любым другим переводчиком. Я готовлю новый релиз, там этот баг будет исправлен. Выкачу в ближайшее время

**Comment by PavlikBender** [comment]
Исправлено в последнем релизе
